#!/usr/bin/env bash
#
# Provision a SoftHSM2 token for the integration suite.
#
#   tests/provision-softhsm.sh
#   SQ_PKCS11_TEST_ENV=tests/softhsm.env uv run pytest
#
# Everything it creates lives under tests/softhsm/ and is gitignored, so this is
# safe to re-run: an existing token and its keys are left alone.  Nothing here
# touches a real HSM, and nothing outside tests/softhsm/ is written.
#
# Needs softhsm2-util (softhsm2) and pkcs11-tool (opensc).
set -euo pipefail

readonly PROG=${0##*/}
REPO=$(cd -- "$(dirname -- "$0")/.." && pwd)
STATE="$REPO/tests/softhsm"

die() {
    printf '%s: %s\n' "$PROG" "$*" >&2
    exit 1
}

for tool in softhsm2-util pkcs11-tool; do
    command -v "$tool" >/dev/null || die "$tool not found.
Debian/Ubuntu: apt install softhsm2 opensc
Fedora/EL:     dnf install softhsm opensc"
done

# The module's location varies by distribution; tests/softhsm.env defaults to
# the Debian/Ubuntu path, so say something when it is elsewhere.
MODULE=
for candidate in \
    /usr/lib/softhsm/libsofthsm2.so \
    /usr/lib64/softhsm/libsofthsm2.so \
    /usr/lib64/pkcs11/libsofthsm2.so \
    /usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so; do
    [[ -e $candidate ]] && { MODULE=$candidate; break; }
done
[[ -n $MODULE ]] || die "could not find libsofthsm2.so; set SOFTHSM_MODULE yourself"

readonly SO_PIN=12345678 PIN=1234 TOKEN_LABEL=sqp11-test

mkdir -p "$STATE/tokens"
export SOFTHSM2_CONF="$STATE/softhsm2.conf"
cat >"$SOFTHSM2_CONF" <<EOF
# Generated by $PROG — edit tests/softhsm.env instead.
directories.tokendir = $STATE/tokens
objectstore.backend = file
log.level = ERROR
EOF
printf '%s' "$PIN" >"$STATE/pin"
chmod 600 "$STATE/pin"

if softhsm2-util --show-slots 2>/dev/null | grep -q "$TOKEN_LABEL"; then
    echo "$PROG: token '$TOKEN_LABEL' already initialised"
else
    softhsm2-util --init-token --free --label "$TOKEN_LABEL" \
        --so-pin "$SO_PIN" --pin "$PIN" >/dev/null
    echo "$PROG: initialised token '$TOKEN_LABEL'"
fi

# The five keys tests/softhsm.env names.  RSA-4096 and P-384 mirror the nShield
# test keys; the P-256 keys stand in for the two-tier primary and subkeys.
existing=$(pkcs11-tool --module "$MODULE" --login --pin "$PIN" --list-objects 2>/dev/null || true)
while read -r keytype label id; do
    [[ -n ${keytype:-} ]] || continue
    if printf '%s' "$existing" | grep -q "label:  *$label\$"; then
        echo "$PROG: key $label already present"
        continue
    fi
    pkcs11-tool --module "$MODULE" --login --pin "$PIN" --keypairgen \
        --key-type "$keytype" --label "$label" --id "$id" >/dev/null
    echo "$PROG: generated $label ($keytype)"
done <<'KEYS'
rsa:4096 sqp11-rsa 01
EC:secp384r1 sqp11-ec 02
EC:prime256v1 sqp11-primary 03
EC:prime256v1 sqp11-subkey 04
EC:prime256v1 sqp11-subkey2 05
KEYS

echo
echo "$PROG: ready.  Run the suite with:"
echo
if [[ $MODULE != /usr/lib/softhsm/libsofthsm2.so ]]; then
    echo "    export SOFTHSM_MODULE=$MODULE   # not the path tests/softhsm.env defaults to"
fi
echo "    SQ_PKCS11_TEST_ENV=tests/softhsm.env uv run pytest"
