mod cert;
mod error;
mod session;
mod signer;

use std::io::Write as IoWrite;
use std::path::PathBuf;

use anyhow::Context;
use clap::{Parser, Subcommand};
use cryptoki::context::{CInitializeArgs, CInitializeFlags, Pkcs11};
use sequoia_openpgp::{
    armor, packet::signature::SignatureBuilder, serialize::stream::*, types::SignatureType,
};

use session::{KeySelector, LoginMode, Pkcs11Uri};
use signer::Pkcs11Signer;

/// `"x.y.z (vX.Y.Z-N-gSHA[-modified])"` — Cargo.toml version plus a `git
/// describe` suffix.  Lets a deployed binary be traced to an exact commit
/// even when the manifest version hasn't been bumped yet.  The `git
/// describe` part is generated by `build.rs`; falls back to "unknown" if
/// the build happens outside a git checkout.
const VERSION: &str = concat!(env!("CARGO_PKG_VERSION"), " (", env!("GIT_DESCRIBE"), ")");

/// OpenPGP signing tool backed by a PKCS#11 HSM.
#[derive(Parser)]
#[command(name = "sq-pkcs11", version = VERSION)]
struct Cli {
    /// Path to the PKCS#11 shared library (vendor module).
    ///
    /// May also be set via the PKCS11_MODULE_PATH environment variable
    /// (standard, used by pkcs11-tool / p11-kit) or SQ_PKCS11_MODULE
    /// (tool-specific fallback, checked when PKCS11_MODULE_PATH is unset).
    #[arg(short = 'm', long, env = "PKCS11_MODULE_PATH", value_name = "PATH")]
    module: Option<PathBuf>,

    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Create a detached OpenPGP signature for a file.
    Sign(SignArgs),
    /// Export the OpenPGP public certificate from an HSM key.
    CertExport(CertExportArgs),
    /// Issue a primary-key revocation certificate.
    CertRevoke(CertRevokeArgs),
    /// Issue a subkey-revocation certificate.
    SubkeyRevoke(SubkeyRevokeArgs),
    /// List signing keys visible in the PKCS#11 token.
    ListKeys(ListKeysArgs),
    /// Verify that an HSM key is a currently-valid signer in a given
    /// certificate.  Pre-flight check against using a stale, revoked,
    /// expired, or unrelated HSM key for production signing.
    VerifySigningKey(VerifySigningKeyArgs),
}

// ---------------------------------------------------------------------------
// Key selection flags — shared between subcommands via flatten.
// ---------------------------------------------------------------------------

#[derive(clap::Args)]
struct KeySelectionArgs {
    /// PKCS#11 URI, e.g. pkcs11:token=release;object=signing-key;type=private
    #[arg(long, group = "key_selector", value_name = "URI")]
    key_uri: Option<String>,

    /// Select key by CKA_LABEL.
    #[arg(long, group = "key_selector", value_name = "LABEL")]
    key_label: Option<String>,

    /// Select key by CKA_ID (hex string, e.g. 01ab02).
    #[arg(long, group = "key_selector", value_name = "HEX")]
    key_id: Option<String>,

    /// Auto-select if exactly one usable key is present.
    #[arg(long, group = "key_selector")]
    auto: bool,
}

impl KeySelectionArgs {
    fn resolve(&self) -> anyhow::Result<KeySelector> {
        if let Some(uri) = &self.key_uri {
            let parsed: Pkcs11Uri = uri.parse()?;
            return Ok(KeySelector::Uri(parsed));
        }
        if let Some(label) = &self.key_label {
            return Ok(KeySelector::Label(label.clone()));
        }
        if let Some(id_hex) = &self.key_id {
            let bytes = hex::decode(id_hex)
                .with_context(|| format!("invalid hex in --key-id: {id_hex}"))?;
            return Ok(KeySelector::Id(bytes));
        }
        if self.auto {
            return Ok(KeySelector::Auto);
        }
        anyhow::bail!("specify one of --key-uri, --key-label, --key-id, or --auto")
    }
}

// ---------------------------------------------------------------------------
// Auth flags — shared between sign and cert-export.
// ---------------------------------------------------------------------------

#[derive(clap::Args)]
struct AuthArgs {
    /// Read the softcard / K=1 OCS passphrase from this file.  A single
    /// trailing newline (CR, LF, or CRLF) is removed; no other characters
    /// are trimmed, so leading or interior whitespace in the passphrase is
    /// preserved.  Omit entirely for module-protected keys.
    ///
    /// As an alternative, the `SQ_PKCS11_PIN` environment variable is read
    /// when this flag is absent.  There is no `--pin <PASS>` value flag
    /// because passphrases on the command line leak through process
    /// listings and shell history.
    ///
    /// For K>1 OCS quorum logins, wrap the sq-pkcs11 invocation in nShield's
    /// `preload` utility — it runs the quorum ceremony, and sq-pkcs11
    /// inherits the preloaded session via the PKCS#11 module.  Omit
    /// `--pin-file` in that case.
    #[arg(long, value_name = "FILE")]
    pin_file: Option<PathBuf>,
}

impl AuthArgs {
    fn login_mode(&self) -> anyhow::Result<LoginMode> {
        if let Some(path) = &self.pin_file {
            return Ok(LoginMode::Pin(read_pin_file(path)?));
        }
        if let Ok(pin) = std::env::var("SQ_PKCS11_PIN") {
            return Ok(LoginMode::Pin(pin));
        }
        Ok(LoginMode::None)
    }
}

/// Read a passphrase from a file: drop the trailing newline (if any),
/// reject totally-empty contents.
fn read_pin_file(path: &std::path::Path) -> anyhow::Result<String> {
    let raw = std::fs::read_to_string(path)
        .with_context(|| format!("reading pin file {}", path.display()))?;
    let pin = raw.trim_end_matches(['\n', '\r']).to_string();
    if pin.is_empty() {
        anyhow::bail!("pin file {} is empty", path.display());
    }
    Ok(pin)
}

// ---------------------------------------------------------------------------
// sign
// ---------------------------------------------------------------------------

#[derive(clap::Args)]
struct SignArgs {
    #[command(flatten)]
    key: KeySelectionArgs,

    #[command(flatten)]
    auth: AuthArgs,

    /// File to sign.
    #[arg(value_name = "FILE")]
    file: PathBuf,

    /// Write signature to this path (default: <input>.asc).  Pass `-` to
    /// stream the signature to stdout instead of writing a file — useful
    /// when the wrapping script (e.g. a `git config gpg.program` shim)
    /// needs to capture the signature without a temp-file dance.
    #[arg(long, short = 'o', value_name = "FILE")]
    output: Option<PathBuf>,

    /// Produce binary signature instead of ASCII-armored.
    /// (Default output is ASCII-armored, matching GnuPG and Sequoia conventions.)
    ///
    /// Binary detached signatures are what `gpg --no-armor -sbo` produces and
    /// what `rpmsign --addsign` embeds verbatim in a package header.
    #[arg(long, conflicts_with = "cleartext")]
    binary: bool,

    /// Emit an OpenPGP Cleartext Signature Framework document (RFC 9580 §7)
    /// instead of a detached signature: the input text, followed by an
    /// armored signature over it, in one file.
    ///
    /// This is the form `gpg --clearsign` produces, and the form apt prefers
    /// for a repository's `InRelease` file.
    ///
    /// `--output` is mandatory here.  A cleartext document is a *signed
    /// message*, not a detached signature, so writing it to the usual
    /// `<input>.asc` default would invite publishing it where a detached
    /// signature is expected — where every verifier would reject it.
    ///
    /// The framework does not sign trailing whitespace and requires a final
    /// newline, so line-ending whitespace is trimmed and a missing final
    /// newline added in the emitted copy of the text; the emitted text is
    /// exactly what was signed.
    #[arg(long, requires = "output")]
    cleartext: bool,

    /// Overwrite the output file if it already exists.  Without this flag,
    /// sq-pkcs11 refuses to overwrite an existing file — protects against
    /// accidentally clobbering a previously-signed release artefact.
    #[arg(long)]
    force: bool,

    /// Key creation time used to compute the OpenPGP fingerprint embedded in
    /// the signature's issuer field (RFC 3339, e.g. 2026-04-30T16:29:30Z).
    ///
    /// Must match the value used during cert-export so verifiers can resolve
    /// the issuer fingerprint to the distributed certificate.
    ///
    /// Precedence: an explicit --creation-time always wins (and warns if it
    /// disagrees with the matching key in --input-cert).  Otherwise, if
    /// --input-cert is given the creation time is derived from the cert.
    /// Supplying neither is an error — there is no default, because a wrong
    /// creation time yields a wrong issuer fingerprint and thus a signature
    /// no verifier can attribute to the published certificate.
    #[arg(long, value_name = "TIMESTAMP")]
    creation_time: Option<String>,

    /// Published certificate to derive the key-creation time from when
    /// --creation-time is not given (RFC 3339 path otherwise).
    ///
    /// The signing (sub)key is located in the cert by matching the HSM key's
    /// public material — RSA modulus+exponent, or EC curve+point — and its
    /// embedded creation time is used so the signature's issuer fingerprint
    /// equals the published (sub)key's by construction.  This is the robust
    /// way to sign release artefacts and git tags: no timestamp to remember,
    /// rotation-safe, and it cannot select the wrong subkey.
    ///
    /// Errors if no key in the cert matches the HSM key's material — it never
    /// silently falls back to the Unix-epoch default.
    #[arg(long, value_name = "FILE")]
    input_cert: Option<PathBuf>,

    /// Refuse to sign unless the HSM key is exactly this algorithm and size.
    ///
    /// A deployment's key policy is not something this tool can infer, and
    /// getting it wrong is expensive to undo: rpm 4.16 (EL9) cannot verify
    /// ECDSA at all, so a package signed with the wrong key type is only
    /// discovered by the consumer.  Stating the requirement at the call site
    /// turns that into a refusal to sign.
    ///
    /// The match is exact, not a minimum: `rsa4096` accepts RSA-4096 and
    /// rejects RSA-3072 *and* RSA-8192.  A policy says which key is in use,
    /// not which keys would be strong enough.
    #[arg(long, value_name = "ALGO", value_enum)]
    require_key_algo: Option<RequiredKeyAlgo>,

    /// Skip the signer-validity pre-flight that --input-cert performs.
    ///
    /// With --input-cert, sign first proves the HSM key is a *current valid
    /// signer* in that certificate — not revoked, not expired, and carrying
    /// the signing flag — because matching the key material alone would still
    /// accept a rotated-out subkey that is deliberately kept in the cert so
    /// old signatures keep verifying.
    ///
    /// Pass this only to sign deliberately with a key the cert no longer
    /// advertises as current; the resulting signature will be rejected by
    /// verifiers applying the same policy.
    #[arg(long, requires = "input_cert")]
    no_verify_signing_key: bool,
}

/// Key algorithms `sign --require-key-algo` can be pinned to.
///
/// Deliberately an enum rather than a free-form string: the values are the
/// algorithms this tool supports at all, so `--help` lists them and a typo is
/// a parse error instead of a policy check that silently never matches.
#[derive(Clone, Copy, Debug, PartialEq, Eq, clap::ValueEnum)]
enum RequiredKeyAlgo {
    Rsa2048,
    Rsa3072,
    Rsa4096,
    P256,
    P384,
    P521,
}

impl RequiredKeyAlgo {
    fn as_str(self) -> &'static str {
        match self {
            Self::Rsa2048 => "RSA-2048",
            Self::Rsa3072 => "RSA-3072",
            Self::Rsa4096 => "RSA-4096",
            Self::P256 => "ECDSA P-256",
            Self::P384 => "ECDSA P-384",
            Self::P521 => "ECDSA P-521",
        }
    }
}

// ---------------------------------------------------------------------------
// cert-export
// ---------------------------------------------------------------------------

#[derive(clap::Args)]
struct CertExportArgs {
    #[command(flatten)]
    key: KeySelectionArgs,

    #[command(flatten)]
    auth: AuthArgs,

    /// User ID to embed, e.g. "OpenSSL Release Key <openssl-security@openssl.org>".
    /// Repeat to add multiple User IDs.  Matches `sq key generate --userid`.
    ///
    /// Required for fresh certs.  Optional with --merge-cert: omitted means
    /// keep the existing cert's UIDs as-is; supplied UIDs are *added*.
    #[arg(
        long = "userid",
        value_name = "USERID",
        required_unless_present = "merge_cert"
    )]
    user_ids: Vec<String>,

    /// Write certificate to this path (default: stdout).
    #[arg(long, short = 'o', value_name = "FILE")]
    output: Option<PathBuf>,

    /// Merge new packets (UIDs and/or subkey) into an existing certificate
    /// rather than building a fresh one.
    ///
    /// Use this for **subkey rotation**: re-running cert-export with a new
    /// `--subkey-label` and the original cert preserves all existing
    /// subkeys (so old signatures keep verifying), revocations, and UIDs,
    /// while adding the new subkey-binding signature.
    ///
    /// The primary fingerprint of the existing cert must match what the
    /// HSM key + `--creation-time` would produce — the tool refuses to
    /// merge across different primary keys.
    #[arg(long, value_name = "FILE")]
    merge_cert: Option<PathBuf>,

    /// Output a binary OpenPGP certificate instead of ASCII-armored.
    #[arg(long)]
    binary: bool,

    /// Overwrite the output file if it already exists.  Without this flag,
    /// sq-pkcs11 refuses to overwrite an existing file — protects against
    /// accidentally clobbering a previously-published certificate.
    #[arg(long)]
    force: bool,

    /// Key creation time to embed in the certificate (RFC 3339,
    /// e.g. 2026-04-30T16:29:30Z).  Required.
    ///
    /// The OpenPGP fingerprint is derived from key material + creation time,
    /// so this value must be used consistently in every subsequent `sign`
    /// invocation.  There is no default: a certificate published with an
    /// accidental placeholder timestamp is permanent, because changing it
    /// changes the fingerprint and so, to every verifier, the key.
    #[arg(long, value_name = "TIMESTAMP")]
    creation_time: Option<String>,

    /// Key validity period, relative to the creation time.
    ///
    /// Format: integer + unit (y = years, w = weeks, d = days, h = hours).
    /// Examples: "5y", "730d", "260w".  Defaults to 5 years.
    ///
    /// `Ny` is calendar-aware: `5y` from 2026-05-10T19:53:26Z expires at
    /// 2031-05-10T19:53:26Z exactly.  Feb 29 falls back to Feb 28 in
    /// non-leap target years.  Other units are exact durations.
    ///
    /// Re-issue the certificate before expiry to extend it.
    #[arg(
        long,
        value_name = "DURATION",
        default_value = "5y",
        group = "validity"
    )]
    validity_period: String,

    /// Issue a certificate with no expiration.
    ///
    /// Mutually exclusive with --validity-period.  Use sparingly: an
    /// expiration bounds the blast radius if the HSM is ever compromised.
    #[arg(long, group = "validity")]
    no_expiration: bool,

    // ────────────────────────────────────────────────────────────────────
    // Optional signing subkey.
    //
    // When a --subkey-* selector is present, the primary key becomes
    // Certify-only and the subkey carries the Sign capability.  Each tier
    // is authenticated independently — typically primary on OCS, subkey
    // module-protected.
    // ────────────────────────────────────────────────────────────────────
    /// Subkey selector — PKCS#11 URI form.
    #[arg(long, value_name = "URI", group = "subkey_selector")]
    subkey_uri: Option<String>,

    /// Subkey selector — by CKA_LABEL.
    #[arg(long, value_name = "LABEL", group = "subkey_selector")]
    subkey_label: Option<String>,

    /// Subkey selector — by CKA_ID (hex).
    #[arg(long, value_name = "HEX", group = "subkey_selector")]
    subkey_id: Option<String>,

    /// Subkey selector — auto-pick when exactly one usable subkey is visible.
    #[arg(long, group = "subkey_selector")]
    subkey_auto: bool,

    /// File containing the subkey passphrase, if it is softcard- or
    /// single-card-OCS-protected.  Same semantics as --pin-file.  The
    /// `SQ_PKCS11_SUBKEY_PIN` environment variable is read when this flag
    /// is absent.  No `--subkey-pin <PASS>` value flag — see --pin-file.
    ///
    /// For K>1 OCS quorum subkeys, wrap the invocation in nShield's
    /// `preload` and omit this flag.
    #[arg(long, value_name = "FILE", requires = "subkey_selector")]
    subkey_pin_file: Option<PathBuf>,

    /// Subkey creation time (RFC 3339).  Same semantics as --creation-time.
    #[arg(long, value_name = "TIMESTAMP", requires = "subkey_selector")]
    subkey_creation_time: Option<String>,

    /// Subkey validity period (default: 2y).  Same format as --validity-period.
    #[arg(
        long,
        value_name = "DURATION",
        default_value = "2y",
        group = "subkey_validity",
        requires = "subkey_selector"
    )]
    subkey_validity_period: String,

    /// Issue the subkey with no expiration.
    #[arg(long, group = "subkey_validity", requires = "subkey_selector")]
    subkey_no_expiration: bool,
}

// ---------------------------------------------------------------------------
// cert-revoke / subkey-revoke
// ---------------------------------------------------------------------------

/// Reasons a key may be revoked, mapping 1:1 to OpenPGP RFC 9580 §5.2.3.31.
#[derive(Debug, Clone, Copy, PartialEq, Eq, clap::ValueEnum)]
enum RevocationReason {
    /// 0x00 — generic revocation, no detail given.
    Unspecified,
    /// 0x01 — the key is being replaced by a new one.
    Superseded,
    /// 0x02 — the secret material is believed to be compromised.
    Compromised,
    /// 0x03 — the key is no longer used (and not replaced).
    Retired,
}

impl From<RevocationReason> for sequoia_openpgp::types::ReasonForRevocation {
    fn from(r: RevocationReason) -> Self {
        use sequoia_openpgp::types::ReasonForRevocation as R;
        match r {
            RevocationReason::Unspecified => R::Unspecified,
            RevocationReason::Superseded => R::KeySuperseded,
            RevocationReason::Compromised => R::KeyCompromised,
            RevocationReason::Retired => R::KeyRetired,
        }
    }
}

#[derive(clap::Args)]
struct CertRevokeArgs {
    #[command(flatten)]
    key: KeySelectionArgs,

    #[command(flatten)]
    auth: AuthArgs,

    /// Primary key creation time used to derive the OpenPGP fingerprint.
    /// Required, and must match the value used during cert-export so the
    /// revocation targets the right key — a revocation aimed at a
    /// fingerprint nobody has is silently useless.
    #[arg(long, value_name = "TIMESTAMP")]
    creation_time: Option<String>,

    /// Revocation reason code.
    #[arg(long, value_enum, value_name = "REASON")]
    reason: RevocationReason,

    /// Free-form human-readable message embedded in the revocation.
    #[arg(long, value_name = "TEXT", default_value = "")]
    message: String,

    /// Time the revocation takes effect (RFC 3339).  Defaults to now.
    #[arg(long, value_name = "TIMESTAMP")]
    revocation_time: Option<String>,

    /// Write revocation to this path (default: stdout).
    #[arg(long, short = 'o', value_name = "FILE")]
    output: Option<PathBuf>,

    /// Output a binary OpenPGP signature packet instead of ASCII-armored.
    #[arg(long)]
    binary: bool,

    /// Overwrite the output file if it already exists.  Without this flag,
    /// sq-pkcs11 refuses to overwrite an existing file — protects against
    /// accidentally clobbering a previously-issued revocation.
    #[arg(long)]
    force: bool,
}

#[derive(clap::Args)]
struct SubkeyRevokeArgs {
    #[command(flatten)]
    key: KeySelectionArgs,

    #[command(flatten)]
    auth: AuthArgs,

    /// Primary key creation time (RFC 3339).  Required — see cert-revoke.
    #[arg(long, value_name = "TIMESTAMP")]
    creation_time: Option<String>,

    /// Path to the published certificate that contains the subkey to be
    /// revoked.  The subkey's public material is read from this cert so
    /// the HSM does not need to hold the subkey's private key — the
    /// signing-subkey's secret can have been deleted, lost, or
    /// compromised.  Only the primary's private key is exercised.
    #[arg(long, value_name = "FILE")]
    input_cert: PathBuf,

    /// Full 40-hex-char OpenPGP fingerprint of the subkey within
    /// --input-cert to revoke.  Whitespace and an optional `0x` prefix
    /// are ignored.  Short 16-hex key IDs are NOT accepted because they
    /// are not collision-resistant — for revocation the unambiguous
    /// fingerprint is required.  Look it up with
    /// `sq inspect <input-cert>` or
    /// `gpg --list-keys --with-subkey-fingerprint`.
    #[arg(long, value_name = "FINGERPRINT")]
    subkey_fingerprint: String,

    /// Revocation reason code.
    #[arg(long, value_enum, value_name = "REASON")]
    reason: RevocationReason,

    /// Free-form human-readable message embedded in the revocation.
    #[arg(long, value_name = "TEXT", default_value = "")]
    message: String,

    /// Time the revocation takes effect (RFC 3339).  Defaults to now.
    #[arg(long, value_name = "TIMESTAMP")]
    revocation_time: Option<String>,

    #[arg(long, short = 'o', value_name = "FILE")]
    output: Option<PathBuf>,

    #[arg(long)]
    binary: bool,

    /// Overwrite the output file if it already exists.  Without this flag,
    /// sq-pkcs11 refuses to overwrite an existing file — protects against
    /// accidentally clobbering a previously-issued revocation.
    #[arg(long)]
    force: bool,
}

// ---------------------------------------------------------------------------
// list-keys
// ---------------------------------------------------------------------------

#[derive(clap::Args)]
struct ListKeysArgs {
    /// Show keys on all slots, not just initialised ones.
    #[arg(long)]
    all_slots: bool,

    /// File containing a PIN to attempt login with (softcard /
    /// single-card OCS).  Same format and rationale as the sign /
    /// cert-export `--pin-file`.  `SQ_PKCS11_PIN` env var is read when
    /// this flag is absent.
    #[arg(long, value_name = "FILE")]
    pin_file: Option<PathBuf>,
}

// ---------------------------------------------------------------------------
// verify-signing-key
// ---------------------------------------------------------------------------

#[derive(clap::Args)]
struct VerifySigningKeyArgs {
    #[command(flatten)]
    key: KeySelectionArgs,

    #[command(flatten)]
    auth: AuthArgs,

    /// Key creation time (RFC 3339) used to derive the OpenPGP fingerprint
    /// of the HSM key — same semantics as in cert-export and sign.
    ///
    /// Required, and deliberately never derived from --input-cert: this
    /// command exists to check that HSM key + declared creation time really
    /// is a live signer in the cert.  Reading the timestamp out of the same
    /// cert would make the check pass by construction.
    #[arg(long, value_name = "TIMESTAMP")]
    creation_time: Option<String>,

    /// Path to the published certificate the HSM key must belong to.
    #[arg(long, value_name = "FILE")]
    input_cert: PathBuf,

    /// Reference time for the cert's policy / liveness checks
    /// (must-not-be-revoked, must-not-be-expired-at-this-time).
    /// Defaults to the current system time.
    #[arg(long, value_name = "TIMESTAMP")]
    at_time: Option<String>,
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();
    let module = resolve_module(cli.module)?;

    let pkcs11 = Pkcs11::new(&module)
        .with_context(|| format!("failed to load PKCS#11 module {}", module.display()))?;
    pkcs11.initialize(CInitializeArgs::new(CInitializeFlags::OS_LOCKING_OK))?;

    match cli.command {
        Command::Sign(args) => cmd_sign(&pkcs11, args),
        Command::CertExport(args) => cmd_cert_export(&pkcs11, args),
        Command::CertRevoke(args) => cmd_cert_revoke(&pkcs11, args),
        Command::SubkeyRevoke(args) => cmd_subkey_revoke(&pkcs11, args),
        Command::ListKeys(args) => cmd_list_keys(&pkcs11, args),
        Command::VerifySigningKey(args) => cmd_verify_signing_key(&pkcs11, args),
    }
}

/// Common interface over args structs that carry a subkey selector +
/// subkey auth pair (cert-export and subkey-revoke).
trait HasSubkeyArgs {
    fn subkey_uri(&self) -> Option<&str>;
    fn subkey_label(&self) -> Option<&str>;
    fn subkey_id(&self) -> Option<&str>;
    fn subkey_auto(&self) -> bool;
    fn subkey_pin_file(&self) -> Option<&std::path::Path>;
}

impl HasSubkeyArgs for CertExportArgs {
    fn subkey_uri(&self) -> Option<&str> {
        self.subkey_uri.as_deref()
    }
    fn subkey_label(&self) -> Option<&str> {
        self.subkey_label.as_deref()
    }
    fn subkey_id(&self) -> Option<&str> {
        self.subkey_id.as_deref()
    }
    fn subkey_auto(&self) -> bool {
        self.subkey_auto
    }
    fn subkey_pin_file(&self) -> Option<&std::path::Path> {
        self.subkey_pin_file.as_deref()
    }
}

/// Resolve the subkey key selector from CLI args.
///
/// Returns `None` if no subkey selector was provided.
fn resolve_subkey_selector<A: HasSubkeyArgs>(args: &A) -> anyhow::Result<Option<KeySelector>> {
    if let Some(uri) = args.subkey_uri() {
        return Ok(Some(KeySelector::Uri(uri.parse()?)));
    }
    if let Some(label) = args.subkey_label() {
        return Ok(Some(KeySelector::Label(label.to_owned())));
    }
    if let Some(id_hex) = args.subkey_id() {
        let bytes =
            hex::decode(id_hex).with_context(|| format!("invalid hex in --subkey-id: {id_hex}"))?;
        return Ok(Some(KeySelector::Id(bytes)));
    }
    if args.subkey_auto() {
        return Ok(Some(KeySelector::Auto));
    }
    Ok(None)
}

/// Build a `LoginMode` for the subkey from --subkey-pin-file or
/// `SQ_PKCS11_SUBKEY_PIN`.
fn build_subkey_login<A: HasSubkeyArgs>(args: &A) -> anyhow::Result<LoginMode> {
    if let Some(path) = args.subkey_pin_file() {
        return Ok(LoginMode::Pin(read_pin_file(path)?));
    }
    if let Ok(pin) = std::env::var("SQ_PKCS11_SUBKEY_PIN") {
        return Ok(LoginMode::Pin(pin));
    }
    Ok(LoginMode::None)
}

/// Return the `Duration` from `creation` to its calendar anniversary `n`
/// years later, with Feb 29 → Feb 28 fallback in non-leap target years.
fn years_from(creation: std::time::SystemTime, n: u32) -> anyhow::Result<std::time::Duration> {
    use chrono::{DateTime, Datelike, Utc};
    let secs = creation
        .duration_since(std::time::UNIX_EPOCH)
        .map_err(|_| anyhow::anyhow!("creation time is before the Unix epoch"))?
        .as_secs() as i64;
    let creation_dt = DateTime::<Utc>::from_timestamp(secs, 0)
        .ok_or_else(|| anyhow::anyhow!("creation time is out of the representable range"))?;
    let new_year = creation_dt
        .year()
        .checked_add(n as i32)
        .ok_or_else(|| anyhow::anyhow!("year arithmetic overflowed ({n}y past creation)"))?;
    let expiration_dt = creation_dt.with_year(new_year).or_else(|| {
        // Feb 29 + N years where (year + N) is not a leap year: fall back to Feb 28.
        creation_dt.with_day(28).and_then(|d| d.with_year(new_year))
    });
    let expiration_dt =
        expiration_dt.ok_or_else(|| anyhow::anyhow!("year arithmetic produced an invalid date"))?;
    let delta = (expiration_dt.timestamp() - creation_dt.timestamp()) as u64;
    Ok(std::time::Duration::from_secs(delta))
}

/// Parse a validity-period string into a `Duration` relative to `creation`.
///
/// Accepts:
/// - `Ny` for years (integer N) — calendar-aware: lands on the same
///   wall-clock time of the same calendar date N years after `creation`.
///   Feb 29 falls back to Feb 28 in non-leap target years.
/// - Anything else is delegated to `humantime` (`Nd`, `Nw`, `Nh`, `5d 12h`, …)
///   and treated as an exact fixed duration.
///
/// The Ny branch needs `creation` because the calendar distance between
/// "now" and "N years from now" depends on which leap years fall in the
/// span.  The old `1y = 365.25 days` Julian-year approximation drifted
/// 6h/year off the wall-clock anniversary; the calendar form removes
/// that.
fn parse_validity(s: &str, creation: std::time::SystemTime) -> anyhow::Result<std::time::Duration> {
    let s = s.trim();
    let dur = if let Some(num_str) = s.strip_suffix('y') {
        let n: u32 = num_str.trim().parse().with_context(|| {
            format!(
                "invalid years value in --validity-period {s:?}: \
                 expected a non-negative integer (e.g. 5y, 10y)"
            )
        })?;
        years_from(creation, n).with_context(|| format!("--validity-period {s:?}"))?
    } else {
        humantime::parse_duration(s).with_context(|| {
            format!("invalid --validity-period {s:?}; use Ny, Nw, Nd, or Nh (e.g. 5y, 60d)")
        })?
    };
    // A zero-duration validity period encodes "expired the moment the
    // signature was made" — almost certainly a fat-finger.  Operators
    // who want an unlimited validity should use --no-expiration; we
    // refuse to silently produce a dead-on-arrival certificate.
    if dur.is_zero() {
        anyhow::bail!(
            "--validity-period {s:?} parses to zero — pass --no-expiration if you \
             want an unlimited validity, or a positive duration like 5y or 365d"
        );
    }
    Ok(dur)
}

/// Parse an RFC 3339 timestamp supplied for `flag`, naming the flag in the
/// error so a bad `--revocation-time` doesn't report itself as a bad
/// `--creation-time`.
fn parse_rfc3339_time(flag: &str, ts: &str) -> anyhow::Result<std::time::SystemTime> {
    humantime::parse_rfc3339(ts)
        .with_context(|| format!("invalid {flag} {ts:?}; use RFC 3339, e.g. 2026-04-30T16:29:30Z"))
}

/// Resolve a **mandatory** OpenPGP key-creation time.
///
/// This used to default to `SystemTime::UNIX_EPOCH` when the flag was
/// omitted.  That default was silent and, in the field, wrong: an OpenPGP
/// fingerprint hashes the creation time along with the key material, so a
/// forgotten flag produced real, well-formed signatures carrying an issuer
/// fingerprint that resolves to no published key.  Verification fails with
/// "no public key" — far away from the actual cause, and only after the
/// artefact has shipped.
///
/// A missing timestamp is therefore an error.  Callers that genuinely want
/// the historical behaviour ask for it in full: `--creation-time
/// 1970-01-01T00:00:00Z`.  No opt-in flag is needed for that, and spelling
/// the epoch out leaves the intent in the caller's command line.
fn require_creation_time(
    supplied: Option<&str>,
    flag: &str,
    derive_hint: Option<&str>,
) -> anyhow::Result<std::time::SystemTime> {
    match supplied {
        Some(ts) => parse_rfc3339_time(flag, ts),
        None => Err(missing_creation_time(flag, derive_hint)),
    }
}

/// The diagnostic for an omitted key-creation time.
///
/// Deliberately long: the value cannot be discovered from the HSM (PKCS#11
/// has no notion of an OpenPGP creation time), so an operator who hits this
/// needs to be told where to go and get it.  `derive_hint` carries the
/// per-command shortcut, if the command has one.
fn missing_creation_time(flag: &str, derive_hint: Option<&str>) -> anyhow::Error {
    let hint = match derive_hint {
        Some(h) => format!("\n{h}\n"),
        None => String::new(),
    };
    anyhow::anyhow!(
        "\
{flag} is required.

An OpenPGP fingerprint is a hash over the public key material *and* the key's
creation time, so this timestamp decides the issuer fingerprint embedded in
whatever is signed.  A PKCS#11 token has no notion of an OpenPGP creation
time, so it cannot be read back off the HSM.

Supply the time the key was generated on the HSM, converted to UTC.  On
nShield that is the Security World `gentime` — see NSHIELD.md, \"Reading the
key generation time from the Security World\", which has a CKA_LABEL-to-RFC
3339 recipe.  The value must equal the creation time the published
certificate embeds for this key.
{hint}
Earlier versions of this tool defaulted to 1970-01-01T00:00:00Z here.  That
silently produced signatures whose issuer fingerprint no verifier could
resolve against the published certificate.  If a certificate really was
published with that default, ask for it explicitly:
`{flag} 1970-01-01T00:00:00Z`."
    )
}

/// Refuse to clobber an existing output file *before* any HSM round
/// trip.  Used by every command that writes file output: an accidental
/// rerun of e.g. `sign` against the same `--output` previously failed
/// only after we'd already asked the HSM to sign — wasted work, and an
/// extraneous key-usage audit-log entry for an attempt that never
/// produced an artefact.  Calling this preflight at the top of each
/// command catches the common case before opening any session.
///
/// `write_or_refuse` still does its own atomic create_new check at write
/// time to close the TOCTOU window.  This helper is the fast path.
fn preflight_overwrite(output: Option<&std::path::Path>, force: bool) -> anyhow::Result<()> {
    if force {
        return Ok(());
    }
    let path = match output {
        Some(p) => p,
        None => return Ok(()),
    };
    // `--output -` means stdout; never a file.
    if path == std::path::Path::new("-") {
        return Ok(());
    }
    // try_exists() distinguishes "exists" from "permission-denied while
    // checking"; the latter we surface as an error rather than a refusal.
    match path.try_exists() {
        Ok(true) => anyhow::bail!(
            "refusing to overwrite existing file {}; pass --force to overwrite",
            path.display()
        ),
        Ok(false) => Ok(()),
        Err(e) => Err(anyhow::Error::from(e).context(format!(
            "checking whether {} already exists",
            path.display()
        ))),
    }
}

/// Write `bytes` to `path`, refusing to overwrite an existing file unless
/// `force` is set.  Used by every command that writes a non-stdout output —
/// signatures, certs, revocation files — so a stale `release.asc` cannot be
/// silently replaced by an accidental rerun.
fn write_or_refuse(path: &std::path::Path, bytes: &[u8], force: bool) -> anyhow::Result<()> {
    use std::io::Write as _;
    let result = if force {
        std::fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .open(path)
    } else {
        std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(path)
    };
    let mut file = result.map_err(|e| {
        if e.kind() == std::io::ErrorKind::AlreadyExists {
            anyhow::anyhow!(
                "refusing to overwrite existing file {}; pass --force to overwrite",
                path.display()
            )
        } else {
            anyhow::Error::from(e).context(format!("opening {} for writing", path.display()))
        }
    })?;
    file.write_all(bytes)
        .with_context(|| format!("writing to {}", path.display()))?;
    Ok(())
}

fn resolve_module(from_cli: Option<PathBuf>) -> anyhow::Result<PathBuf> {
    if let Some(p) = from_cli {
        return Ok(p);
    }
    // PKCS11_MODULE_PATH already handled by clap env; reaching here means it
    // was unset. Check the tool-specific fallback variable.
    if let Ok(val) = std::env::var("SQ_PKCS11_MODULE") {
        return Ok(PathBuf::from(val));
    }
    anyhow::bail!(
        "PKCS#11 module not specified.\n\
         Use -m/--module <path>, or set PKCS11_MODULE_PATH or SQ_PKCS11_MODULE.\n\
         Example: -m /opt/nfast/toolkits/pkcs11/libcknfast.so"
    )
}

// ---------------------------------------------------------------------------
// sign
// ---------------------------------------------------------------------------

fn cmd_sign(pkcs11: &Pkcs11, args: SignArgs) -> anyhow::Result<()> {
    let selector = args.key.resolve()?;
    let login = args.auth.login_mode()?;

    // The creation time has to come from somewhere: either stated outright,
    // or read out of a published cert.  Reject "neither" up front, before any
    // HSM round-trip, rather than falling back to a placeholder that would
    // produce a correctly-signed artefact attributed to a key nobody has.
    if args.creation_time.is_none() && args.input_cert.is_none() {
        return Err(missing_creation_time(
            "--creation-time",
            Some(
                "Or skip the timestamp entirely and pass `--input-cert <CERT>`: sign then\n\
                 locates the key in that certificate by matching the HSM key's public\n\
                 material and reuses its creation time, so the issuer fingerprint matches\n\
                 the published key by construction.  This is the preferred form.",
            ),
        ));
    }

    // An explicit --creation-time, parsed now so a malformed timestamp fails
    // before any HSM round-trip.  `None` here means "not supplied", which the
    // precedence logic below needs to distinguish from a supplied value.
    let explicit_creation_time = args
        .creation_time
        .as_deref()
        .map(|s| parse_rfc3339_time("--creation-time", s))
        .transpose()?;

    // Resolve the output path first, then preflight the overwrite check
    // BEFORE opening the HSM session.  Without this, an accidental
    // rerun against the same `--output` would consume an HSM signing
    // operation (and the corresponding key-usage audit-log entry)
    // before failing on the existing file.
    let output_target = match args.output.as_deref() {
        Some(p) if p == std::path::Path::new("-") => SignOutput::Stdout,
        Some(p) => SignOutput::File(p.to_path_buf()),
        None => {
            let mut p = args.file.clone();
            let new_ext = match p.extension().and_then(|e| e.to_str()) {
                Some(ext) => format!("{ext}.asc"),
                None => "asc".into(),
            };
            p.set_extension(new_ext);
            SignOutput::File(p)
        }
    };
    if let SignOutput::File(path) = &output_target {
        preflight_overwrite(Some(path), args.force)?;
    }

    // Parse --input-cert (if any) before any HSM round-trip so a malformed
    // cert fails fast.
    let input_cert = match args.input_cert.as_deref() {
        Some(path) => {
            let bytes = std::fs::read(path)
                .with_context(|| format!("reading --input-cert {}", path.display()))?;
            Some(cert::parse_cert(&bytes)?)
        }
        None => None,
    };

    let (session, _slot) = session::open_session(pkcs11, &selector, &login)?;
    let priv_handle = session::resolve_single_key(&session, &selector)?;
    let mut signer = Pkcs11Signer::new(session, priv_handle)?;

    // Determine the OpenPGP key-creation time to sign with, by precedence:
    //   1. explicit --creation-time wins (warn if it disagrees with the
    //      matching key in --input-cert);
    //   2. else derive from --input-cert by matching public material.
    // "Neither supplied" was rejected in the preflight above.
    // `signer.public_key()` carries the HSM key's material; its (epoch)
    // creation time here is irrelevant to matching, which is material-only.
    let creation_time = match (explicit_creation_time, &input_cert) {
        (Some(explicit), Some(cert)) => {
            if let Ok(derived) = cert::creation_time_of_matching_key(cert, signer.public_key()) {
                if derived != explicit {
                    eprintln!(
                        "warning: --creation-time {} disagrees with the matching key's \
                         creation time in --input-cert ({}); signing with --creation-time \
                         as given — the signature may not verify against that cert",
                        humantime::format_rfc3339(explicit),
                        humantime::format_rfc3339(derived),
                    );
                }
            }
            explicit
        }
        (Some(explicit), None) => explicit,
        (None, Some(cert)) => cert::creation_time_of_matching_key(cert, signer.public_key())?,
        (None, None) => unreachable!("the preflight above rejects both being absent"),
    };
    signer.set_creation_time(creation_time)?;

    // Both checks below run before the first signing operation, so a refusal
    // costs nothing: no signature is produced and no key-usage entry is
    // written to the HSM's audit log.
    if let Some(required) = args.require_key_algo {
        if !key_matches_algo(signer.public_key(), required) {
            anyhow::bail!(
                "--require-key-algo {} was given, but the selected key is {}.\n\
                 Nothing was signed.  Either the wrong key was selected, or the \
                 policy names the wrong algorithm.",
                required.as_str(),
                describe_key_algo(signer.public_key()),
            );
        }
    }

    // With a cert in hand, prove the key is still a *current* signer in it
    // before signing anything.  Deriving the creation time from the cert
    // (above) only proves the key is present, and an old subkey stays present
    // on purpose so its past signatures keep verifying — so material matching
    // alone would happily sign with a rotated-out, revoked or expired key and
    // produce an artefact that every policy-applying verifier rejects.
    if let Some(cert) = &input_cert {
        if !args.no_verify_signing_key {
            let cert_path = args
                .input_cert
                .as_deref()
                .expect("input_cert parsed, so the path was given");
            require_current_signer(
                cert,
                signer.public_key(),
                creation_time,
                std::time::SystemTime::now(),
                cert_path,
            )
            .context(
                "refusing to sign: the key is not a current valid signer in --input-cert \
                 (pass --no-verify-signing-key to sign anyway)",
            )?;
        }
    }

    // Pick the hash algorithm to match the signing key strength — same
    // policy used for cert self-signatures (cert::preferred_hash_for).
    let hash_algo = cert::preferred_hash_for(signer.public_key());

    let data =
        std::fs::read(&args.file).with_context(|| format!("reading {}", args.file.display()))?;

    // Only the --binary path departs from the streaming signer, so only it
    // needs the signature's own creation time pinned up front.  See that
    // branch, and cert::with_noncritical_creation_time.
    let sig_buf = if args.cleartext {
        // Cleartext Signature Framework: Sequoia's streaming signer emits the
        // whole document — `-----BEGIN PGP SIGNED MESSAGE-----`, the Hash
        // header, the dash-escaped text, then the armored signature.  It must
        // NOT be wrapped in an Armorer (that would armor the armor), and it
        // forces SignatureType::Text internally; we state Text in the template
        // too so the code reads the way the output does.
        let mut buf = Vec::new();
        {
            let sink = Message::new(&mut buf);
            let template = SignatureBuilder::new(SignatureType::Text).set_hash_algo(hash_algo);
            // .hash_algo() as well as the template: Signer::with_template does
            // not take the message hash from the template — it keeps its own
            // field, unset by default, which falls back to the first entry of
            // default_hashes() (SHA-512).  Setting only the template silently
            // signs a P-384 key under SHA-512.
            let mut signing_stream = Signer::with_template(sink, signer, template)?
                .hash_algo(hash_algo)?
                .cleartext()
                .build()?;
            signing_stream.write_all(&data)?;
            signing_stream.finalize()?;
        }
        buf
    } else if args.binary {
        // A detached signature is exactly one Signature packet over the data,
        // so build it from the template directly instead of streaming.  The
        // streaming path calls set_signature_creation_time() itself after
        // cloning the template (serialize::stream, emit_signatures), which
        // re-marks that subpacket critical — and rpm's own parser, through
        // 4.16, cannot read it in that form.  See
        // cert::with_noncritical_creation_time.
        //
        // This is deliberately scoped to --binary, the only form rpm consumes.
        // The armored branch below is left on the streaming signer so that the
        // signatures over release tarballs and git tags keep running through
        // exactly the code that produced them before, byte-shape and all; no
        // consumer of those reads the creation time through a parser that gets
        // the critical bit wrong.  Nothing is lost by not streaming here: the
        // input is already in memory, and a signature cannot be emitted before
        // its last byte has been hashed anyway.
        let template = cert::with_noncritical_creation_time(
            SignatureBuilder::new(SignatureType::Binary).set_hash_algo(hash_algo),
            std::time::SystemTime::now(),
        )?;
        let sig = template.sign_message(&mut signer, &data)?;
        cert::export_binary_signature(&sig)?
    } else {
        let mut buf = Vec::new();
        {
            let sink = Message::new(&mut buf);
            // Armorer defaults to Kind::Message which would emit
            // `-----BEGIN PGP MESSAGE-----`.  A detached signature must be
            // wrapped in Kind::Signature so verifiers (and `sq inspect`) see
            // `-----BEGIN PGP SIGNATURE-----` and treat the bytes as a
            // standalone signature rather than an OpenPGP message.
            let sink = Armorer::new(sink).kind(armor::Kind::Signature).build()?;
            let template = SignatureBuilder::new(SignatureType::Binary).set_hash_algo(hash_algo);
            // See the cleartext branch: the template alone does not set the
            // message hash on a streaming signer.
            let mut signing_stream = Signer::with_template(sink, signer, template)?
                .hash_algo(hash_algo)?
                .detached()
                .build()?;
            signing_stream.write_all(&data)?;
            signing_stream.finalize()?;
        }
        buf
    };

    let what = if args.cleartext {
        "Cleartext-signed message"
    } else {
        "Signature"
    };
    match output_target {
        SignOutput::Stdout => {
            std::io::stdout()
                .write_all(&sig_buf)
                .with_context(|| format!("writing {} to stdout", what.to_lowercase()))?;
        }
        SignOutput::File(sig_path) => {
            write_or_refuse(&sig_path, &sig_buf, args.force)?;
            eprintln!("{what} written to {}", sig_path.display());
        }
    }
    Ok(())
}

enum SignOutput {
    Stdout,
    File(PathBuf),
}

// ---------------------------------------------------------------------------
// cert-export
// ---------------------------------------------------------------------------

fn cmd_cert_export(pkcs11: &Pkcs11, args: CertExportArgs) -> anyhow::Result<()> {
    // Preflight overwrite before any HSM round trip.  cert-export
    // produces multiple signatures (direct-key, every UID binding, and
    // the subkey binding + cross-sig if a subkey is requested) — wasting
    // all of those against an existing file is especially expensive.
    preflight_overwrite(args.output.as_deref(), args.force)?;

    // ── Primary tier ─────────────────────────────────────────────────
    let primary_selector = args.key.resolve()?;
    let primary_login = args.auth.login_mode()?;
    let primary_creation_time = require_creation_time(
        args.creation_time.as_deref(),
        "--creation-time",
        Some(
            "For a rotation with --merge-cert this is the *existing* primary's creation\n\
             time: the primary fingerprint is the certificate's identity, and the merge is\n\
             refused outright if the two disagree.",
        ),
    )?;
    let primary_validity = if args.no_expiration {
        None
    } else {
        Some(parse_validity(
            &args.validity_period,
            primary_creation_time,
        )?)
    };

    let (primary_session, _) = session::open_session(pkcs11, &primary_selector, &primary_login)?;
    let primary_handle = session::resolve_single_key(&primary_session, &primary_selector)?;
    let mut primary_signer = Pkcs11Signer::new(primary_session, primary_handle)?;

    // ── Optional subkey tier ─────────────────────────────────────────
    let subkey_selector = resolve_subkey_selector(&args)?;
    let mut subkey_signer_holder: Option<Pkcs11Signer> = None;
    let subkey_creation_time;
    let subkey_validity;

    if let Some(sel) = &subkey_selector {
        let subkey_login = build_subkey_login(&args)?;
        subkey_creation_time = require_creation_time(
            args.subkey_creation_time.as_deref(),
            "--subkey-creation-time",
            Some(
                "This is the new signing subkey's own creation time — the one every later\n\
                 `sign --creation-time` for that subkey has to repeat.  It is independent of\n\
                 the primary's, and for a rotation it is usually the cut-over date.",
            ),
        )?;
        subkey_validity = if args.subkey_no_expiration {
            None
        } else {
            Some(parse_validity(
                &args.subkey_validity_period,
                subkey_creation_time,
            )?)
        };
        let (sk_session, _) = session::open_session(pkcs11, sel, &subkey_login)?;
        let sk_handle = session::resolve_single_key(&sk_session, sel)?;
        subkey_signer_holder = Some(Pkcs11Signer::new(sk_session, sk_handle)?);
    } else {
        // Unused but the compiler requires they be initialised on all paths.
        subkey_creation_time = std::time::SystemTime::UNIX_EPOCH;
        subkey_validity = None;
    }

    // ── Assemble the cert spec and build ─────────────────────────────
    let primary_spec = cert::KeySpec {
        signer: &mut primary_signer,
        creation_time: primary_creation_time,
        validity_period: primary_validity,
    };
    let subkey_spec = subkey_signer_holder.as_mut().map(|signer| cert::KeySpec {
        signer,
        creation_time: subkey_creation_time,
        validity_period: subkey_validity,
    });

    // ── Optionally read the existing cert for merge mode ────────────────
    let merge_into = match &args.merge_cert {
        Some(path) => {
            let bytes = std::fs::read(path)
                .with_context(|| format!("reading existing cert {}", path.display()))?;
            Some(cert::parse_cert(&bytes)?)
        }
        None => None,
    };

    let spec = cert::CertSpec {
        primary: primary_spec,
        subkey: subkey_spec,
        user_ids: &args.user_ids,
        merge_into: merge_into.as_ref(),
    };

    let cert = cert::build_cert(spec)?;

    if args.binary {
        let bytes = cert::export_binary_cert(&cert)?;
        match args.output {
            Some(path) => {
                write_or_refuse(&path, &bytes, args.force)?;
                eprintln!("Certificate written to {}", path.display());
            }
            None => std::io::stdout().write_all(&bytes)?,
        }
    } else {
        let armored = cert::export_armored_cert(&cert)?;
        match args.output {
            Some(path) => {
                write_or_refuse(&path, armored.as_bytes(), args.force)?;
                eprintln!("Certificate written to {}", path.display());
            }
            None => print!("{armored}"),
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// cert-revoke
// ---------------------------------------------------------------------------

fn cmd_cert_revoke(pkcs11: &Pkcs11, args: CertRevokeArgs) -> anyhow::Result<()> {
    // Preflight overwrite before opening any HSM session.
    preflight_overwrite(args.output.as_deref(), args.force)?;

    let selector = args.key.resolve()?;
    let login = args.auth.login_mode()?;
    let creation_time = require_creation_time(
        args.creation_time.as_deref(),
        "--creation-time",
        Some("This is the *primary* key's creation time, as published in the certificate."),
    )?;
    let revocation_time = match args.revocation_time.as_deref() {
        Some(s) => parse_rfc3339_time("--revocation-time", s)?,
        None => std::time::SystemTime::now(),
    };

    let (session, _) = session::open_session(pkcs11, &selector, &login)?;
    let handle = session::resolve_single_key(&session, &selector)?;
    let mut signer = Pkcs11Signer::new(session, handle)?;

    let spec = cert::CertRevocationSpec {
        primary: cert::KeySpec {
            signer: &mut signer,
            creation_time,
            validity_period: None,
        },
        reason: args.reason.into(),
        message: args.message.as_bytes(),
        revocation_time,
    };

    let sig = cert::build_cert_revocation(spec)?;
    write_revocation_output(&sig, args.binary, args.output.as_deref(), args.force)
}

// ---------------------------------------------------------------------------
// subkey-revoke
// ---------------------------------------------------------------------------

fn cmd_subkey_revoke(pkcs11: &Pkcs11, args: SubkeyRevokeArgs) -> anyhow::Result<()> {
    let primary_selector = args.key.resolve()?;
    let primary_login = args.auth.login_mode()?;
    let primary_creation_time = require_creation_time(
        args.creation_time.as_deref(),
        "--creation-time",
        Some(
            "This is the *primary* key's creation time — the subkey being revoked is\n\
             identified by --subkey-fingerprint out of --input-cert, not by a timestamp.",
        ),
    )?;
    let revocation_time = match args.revocation_time.as_deref() {
        Some(s) => parse_rfc3339_time("--revocation-time", s)?,
        None => std::time::SystemTime::now(),
    };

    // Preflight: refuse to overwrite output BEFORE any HSM round trip
    // so an accidental rerun does not consume an HSM signing operation
    // (and the corresponding key-usage audit-log entry).
    preflight_overwrite(args.output.as_deref(), args.force)?;

    // Parse the cert, parse the fingerprint, locate the subkey.  No HSM
    // access yet — these are all local checks.
    let target_fpr = parse_full_fingerprint(&args.subkey_fingerprint)?;
    let cert_bytes = std::fs::read(&args.input_cert)
        .with_context(|| format!("reading --input-cert {}", args.input_cert.display()))?;
    let cert = cert::parse_cert(&cert_bytes)?;
    let subkey_public = locate_subkey_in_cert(&cert, &target_fpr)?;

    let (primary_session, _) = session::open_session(pkcs11, &primary_selector, &primary_login)?;
    let primary_handle = session::resolve_single_key(&primary_session, &primary_selector)?;
    let mut primary_signer = Pkcs11Signer::new(primary_session, primary_handle)?;
    primary_signer.set_creation_time(primary_creation_time)?;

    // Verify the HSM-derived primary fingerprint matches the cert's
    // primary fingerprint.  Without this check, an operator who picks
    // the wrong --key-label (or the right label with the wrong
    // --creation-time) could produce a revocation signed by primary A
    // for a subkey of cert B — a footgun that wastes an HSM signing
    // operation and may not even fail loudly downstream.
    let hsm_primary = sequoia_openpgp::packet::Key::V4(sequoia_openpgp::packet::key::Key4::<
        sequoia_openpgp::packet::key::PublicParts,
        sequoia_openpgp::packet::key::PrimaryRole,
    >::new(
        primary_creation_time,
        primary_signer.public_key().pk_algo(),
        primary_signer.public_key().mpis().clone(),
    )?);
    let hsm_fpr = hsm_primary.fingerprint();
    let cert_fpr = cert.primary_key().key().fingerprint();
    if hsm_fpr != cert_fpr {
        anyhow::bail!(
            "primary fingerprint mismatch: --input-cert primary is {cert_fpr}, \
             selected HSM primary is {hsm_fpr} \
             (check --key-label/--creation-time match the input cert)"
        );
    }

    let spec = cert::SubkeyRevocationSpec {
        primary: cert::KeySpec {
            signer: &mut primary_signer,
            creation_time: primary_creation_time,
            validity_period: None,
        },
        subkey_public,
        reason: args.reason.into(),
        message: args.message.as_bytes(),
        revocation_time,
    };

    let sig = cert::build_subkey_revocation(spec)?;
    write_revocation_output(&sig, args.binary, args.output.as_deref(), args.force)
}

/// Parse a 40-hex-char OpenPGP fingerprint, with whitespace and an
/// optional `0x` prefix stripped (handles strings copy-pasted from
/// `gpg --fingerprint` output).
///
/// Short 16-hex key IDs are intentionally NOT accepted: revocation is
/// rare and high-stakes, and a hostile or malformed cert can carry a
/// secondary subkey whose key ID aliases another, silently shifting
/// the revocation to the wrong subkey.  Requiring the full fingerprint
/// removes that ambiguity at the cost of a longer paste.
fn parse_full_fingerprint(needle: &str) -> anyhow::Result<sequoia_openpgp::Fingerprint> {
    let cleaned: String = needle
        .chars()
        .filter(|c| !c.is_whitespace())
        .collect::<String>()
        .trim_start_matches("0x")
        .trim_start_matches("0X")
        .to_string();
    if cleaned.len() != 40 {
        anyhow::bail!(
            "{needle:?} is not a full OpenPGP fingerprint (got {} hex chars after \
             stripping whitespace and 0x prefix; need exactly 40); short 16-char \
             key IDs are not accepted because they are not collision-resistant",
            cleaned.len()
        );
    }
    sequoia_openpgp::Fingerprint::from_hex(&cleaned)
        .with_context(|| format!("parsing {needle:?} as a 40-hex-char fingerprint"))
}

/// Locate a subkey within an already-parsed cert by full fingerprint.
fn locate_subkey_in_cert(
    cert: &sequoia_openpgp::Cert,
    fingerprint: &sequoia_openpgp::Fingerprint,
) -> anyhow::Result<
    sequoia_openpgp::packet::Key<
        sequoia_openpgp::packet::key::PublicParts,
        sequoia_openpgp::packet::key::SubordinateRole,
    >,
> {
    for sub in cert.keys().subkeys() {
        let key = sub.key();
        if &key.fingerprint() == fingerprint {
            return Ok(key.clone().role_into_subordinate());
        }
    }
    anyhow::bail!("no subkey in the input cert matches fingerprint {fingerprint}")
}

/// Shared output handler for cert-revoke and subkey-revoke.
fn write_revocation_output(
    sig: &sequoia_openpgp::packet::Signature,
    binary: bool,
    output: Option<&std::path::Path>,
    force: bool,
) -> anyhow::Result<()> {
    if binary {
        let bytes = cert::export_binary_signature(sig)?;
        match output {
            Some(path) => {
                write_or_refuse(path, &bytes, force)?;
                eprintln!("Revocation written to {}", path.display());
            }
            None => std::io::stdout().write_all(&bytes)?,
        }
    } else {
        let armored = cert::export_armored_signature(sig)?;
        match output {
            Some(path) => {
                write_or_refuse(path, armored.as_bytes(), force)?;
                eprintln!("Revocation written to {}", path.display());
            }
            None => print!("{armored}"),
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// verify-signing-key
// ---------------------------------------------------------------------------

/// Algorithm and size of an HSM public key, in the vocabulary
/// `--require-key-algo` uses.
fn describe_key_algo(
    public: &sequoia_openpgp::packet::Key<
        sequoia_openpgp::packet::key::PublicParts,
        sequoia_openpgp::packet::key::UnspecifiedRole,
    >,
) -> String {
    use sequoia_openpgp::crypto::mpi;
    use sequoia_openpgp::types::Curve;
    match public.mpis() {
        mpi::PublicKey::RSA { n, .. } => format!("RSA-{}", n.bits()),
        mpi::PublicKey::ECDSA { curve, .. } => match curve {
            Curve::NistP256 => "ECDSA P-256".to_string(),
            Curve::NistP384 => "ECDSA P-384".to_string(),
            Curve::NistP521 => "ECDSA P-521".to_string(),
            other => format!("ECDSA {other}"),
        },
        _ => format!("{}", public.pk_algo()),
    }
}

/// Whether an HSM key is exactly the algorithm and size a policy pinned.
///
/// Matched structurally rather than by comparing rendered strings: this
/// decides whether a release gets signed, and a formatting change must not be
/// able to turn it into a check that silently never matches.
fn key_matches_algo(
    public: &sequoia_openpgp::packet::Key<
        sequoia_openpgp::packet::key::PublicParts,
        sequoia_openpgp::packet::key::UnspecifiedRole,
    >,
    required: RequiredKeyAlgo,
) -> bool {
    use sequoia_openpgp::crypto::mpi;
    use sequoia_openpgp::types::Curve;
    match (public.mpis(), required) {
        (mpi::PublicKey::RSA { n, .. }, RequiredKeyAlgo::Rsa2048) => n.bits() == 2048,
        (mpi::PublicKey::RSA { n, .. }, RequiredKeyAlgo::Rsa3072) => n.bits() == 3072,
        (mpi::PublicKey::RSA { n, .. }, RequiredKeyAlgo::Rsa4096) => n.bits() == 4096,
        (
            mpi::PublicKey::ECDSA {
                curve: Curve::NistP256,
                ..
            },
            RequiredKeyAlgo::P256,
        ) => true,
        (
            mpi::PublicKey::ECDSA {
                curve: Curve::NistP384,
                ..
            },
            RequiredKeyAlgo::P384,
        ) => true,
        (
            mpi::PublicKey::ECDSA {
                curve: Curve::NistP521,
                ..
            },
            RequiredKeyAlgo::P521,
        ) => true,
        _ => false,
    }
}

/// The OpenPGP fingerprint an HSM key has when stamped with `creation_time`.
fn hsm_key_fingerprint(
    public: &sequoia_openpgp::packet::Key<
        sequoia_openpgp::packet::key::PublicParts,
        sequoia_openpgp::packet::key::UnspecifiedRole,
    >,
    creation_time: std::time::SystemTime,
) -> anyhow::Result<sequoia_openpgp::Fingerprint> {
    let key =
        sequoia_openpgp::packet::Key::V4(sequoia_openpgp::packet::key::Key4::<
            sequoia_openpgp::packet::key::PublicParts,
            sequoia_openpgp::packet::key::PrimaryRole,
        >::new(
            creation_time, public.pk_algo(), public.mpis().clone()
        )?);
    Ok(key.fingerprint())
}

/// Prove the HSM key, stamped with `creation_time`, is a *current valid
/// signer* in `cert` at `at_time`.
///
/// Shared by `verify-signing-key` and by `sign`'s `--input-cert` pre-flight so
/// the two can never disagree about what "valid signer" means.
///
/// Note what matching key material alone would miss: an old subkey stays in a
/// published cert on purpose, so signatures it made keep verifying.  Material
/// matching therefore accepts a rotated-out key happily; only a policy check
/// at a reference time rejects it.
fn require_current_signer(
    cert: &sequoia_openpgp::Cert,
    public: &sequoia_openpgp::packet::Key<
        sequoia_openpgp::packet::key::PublicParts,
        sequoia_openpgp::packet::key::UnspecifiedRole,
    >,
    creation_time: std::time::SystemTime,
    at_time: std::time::SystemTime,
    cert_path: &std::path::Path,
) -> anyhow::Result<sequoia_openpgp::Fingerprint> {
    use sequoia_openpgp::policy::StandardPolicy;
    use sequoia_openpgp::types::KeyFlags;

    let hsm_fpr = hsm_key_fingerprint(public, creation_time)?;

    // Apply Sequoia's StandardPolicy at the chosen reference time.
    // ValidCert::keys() yields keys whose binding signatures are valid
    // under that policy at that time.  Filtering on .alive() rejects
    // expired keys; .revoked(false) rejects revoked keys; key_flags()
    // restricts to signing-capable.
    //
    // We accept BOTH the primary and any subkey as a valid match: a
    // single-tier cert (no subkeys, primary carries the signing flag)
    // is a reasonable deployment that we shouldn't reject here.  Any
    // policy that requires a specific structure (e.g. "release artefacts
    // must be signed by a subkey, never the primary") belongs in the
    // operator's wrapper, not in this generic primitive.
    let policy = StandardPolicy::new();
    let valid = cert.with_policy(&policy, at_time).with_context(|| {
        format!(
            "input cert {} fails StandardPolicy validation at {}",
            cert_path.display(),
            humantime::format_rfc3339(at_time),
        )
    })?;

    let signing_flag = KeyFlags::empty().set_signing();
    let candidates: Vec<_> = valid
        .keys()
        .alive()
        .revoked(false)
        .key_flags(signing_flag)
        .collect();

    if candidates.iter().any(|k| k.key().fingerprint() == hsm_fpr) {
        return Ok(hsm_fpr);
    }

    // No match.  Distinguish "key isn't bound at all" (operator picked
    // the wrong --key-label / --creation-time, or the wrong cert) from
    // "key is bound but isn't currently a valid signer" (revoked,
    // expired, or signing flag missing).  Different operator fixes.
    let bound_at_all = cert.keys().any(|k| k.key().fingerprint() == hsm_fpr);
    if bound_at_all {
        anyhow::bail!(
            "HSM key {hsm_fpr} is present in {} but is not currently a valid signer \
             at {} (revoked, expired, or not signing-capable); \
             current valid signing keys: [{}]",
            cert_path.display(),
            humantime::format_rfc3339(at_time),
            candidates
                .iter()
                .map(|k| k.key().fingerprint().to_string())
                .collect::<Vec<_>>()
                .join(", "),
        );
    } else {
        anyhow::bail!(
            "HSM key {hsm_fpr} is not bound to {} at all; \
             either --key-label / --creation-time disagree with the cert, \
             or the wrong cert was supplied",
            cert_path.display(),
        );
    }
}

fn cmd_verify_signing_key(pkcs11: &Pkcs11, args: VerifySigningKeyArgs) -> anyhow::Result<()> {
    let selector = args.key.resolve()?;
    let login = args.auth.login_mode()?;
    let creation_time = require_creation_time(
        args.creation_time.as_deref(),
        "--creation-time",
        Some(
            "Pass the same value the matching `sign` invocation will use — checking a\n\
             different timestamp than you sign with tells you nothing.",
        ),
    )?;
    let at_time = match args.at_time.as_deref() {
        Some(s) => parse_rfc3339_time("--at-time", s)?,
        None => std::time::SystemTime::now(),
    };

    // Parse the cert before any HSM round-trip so a malformed cert
    // input fails immediately rather than after using a session.
    let cert_bytes = std::fs::read(&args.input_cert)
        .with_context(|| format!("reading --input-cert {}", args.input_cert.display()))?;
    let cert = cert::parse_cert(&cert_bytes)?;

    // Open the HSM session, read the public material, stamp it with
    // the declared creation time so its fingerprint matches what the
    // cert would carry.
    let (session, _) = session::open_session(pkcs11, &selector, &login)?;
    let priv_handle = session::resolve_single_key(&session, &selector)?;
    let mut signer = Pkcs11Signer::new(session, priv_handle)?;
    signer.set_creation_time(creation_time)?;

    let hsm_fpr = require_current_signer(
        &cert,
        signer.public_key(),
        creation_time,
        at_time,
        &args.input_cert,
    )?;
    println!(
        "OK: HSM key {hsm_fpr} ({}) is a current signing key in {}",
        describe_key_algo(signer.public_key()),
        args.input_cert.display()
    );
    Ok(())
}

// ---------------------------------------------------------------------------
// list-keys
// ---------------------------------------------------------------------------

fn cmd_list_keys(pkcs11: &Pkcs11, args: ListKeysArgs) -> anyhow::Result<()> {
    use cryptoki::object::{Attribute, AttributeType, ObjectClass};
    use cryptoki::session::UserType;
    use cryptoki::types::AuthPin;

    // Resolve the optional PIN once: --pin-file beats env var.
    let pin: Option<String> = match &args.pin_file {
        Some(path) => Some(read_pin_file(path)?),
        None => std::env::var("SQ_PKCS11_PIN").ok(),
    };

    let slots = if args.all_slots {
        pkcs11.get_all_slots()?
    } else {
        pkcs11.get_slots_with_initialized_token()?
    };

    if slots.is_empty() {
        println!("No slots found.");
        return Ok(());
    }

    for slot in slots {
        let token_info = pkcs11.get_token_info(slot);

        // Skip empty card reader slots when listing — they have no token.
        if token_info.is_err() {
            if args.all_slots {
                println!("Slot {}  [no token present]", slot.id());
            }
            continue;
        }
        let info = token_info.unwrap();
        let token_label = info.label().trim().to_string();
        let protection = if info.login_required() {
            "token-protected (OCS or softcard)"
        } else {
            "module-protected"
        };
        println!("Slot {}  token: {token_label}  [{protection}]", slot.id());

        let session = match pkcs11.open_ro_session(slot) {
            Ok(s) => s,
            Err(e) => {
                println!("  (could not open session: {e})");
                continue;
            }
        };

        if let Some(p) = &pin {
            let _ = session.login(UserType::User, Some(&AuthPin::from(p.clone())));
        } else if info.login_required() {
            // No PIN provided but the slot requires login.  Try a NULL-PIN
            // C_Login to pick up a credential preloaded by an external
            // tool (e.g. nShield's `preload`).  Best-effort — if it
            // fails the slot just shows "(no signing keys)" as before.
            let _ = session.login(UserType::User, None);
        }

        let handles = session.find_objects(&[
            Attribute::Class(ObjectClass::PRIVATE_KEY),
            Attribute::Sign(true),
        ])?;

        if handles.is_empty() {
            println!("  (no signing keys)");
            continue;
        }

        for handle in handles {
            let label = get_str_attr(&session, handle, AttributeType::Label)
                .unwrap_or_else(|| "<no label>".into());
            // Treat both "no Id attribute" and "Id attribute with zero
            // bytes" as missing — nShield assigns an empty CKA_ID to some
            // EC keys, and a literal `id=` followed by whitespace would
            // confuse downstream parsers (e.g. the integration tests that
            // grep this output for the hex id of a label).
            let id = session
                .get_attributes(handle, &[AttributeType::Id])
                .ok()
                .and_then(|attrs| {
                    attrs.into_iter().find_map(|a| match a {
                        Attribute::Id(v) if !v.is_empty() => Some(hex::encode(v)),
                        _ => None,
                    })
                })
                .unwrap_or_else(|| "<no id>".into());
            let key_type = session
                .get_attributes(handle, &[AttributeType::KeyType])
                .ok()
                .and_then(|attrs| {
                    attrs.into_iter().find_map(|a| match a {
                        Attribute::KeyType(kt) => Some(key_type_name(kt)),
                        _ => None,
                    })
                })
                .unwrap_or_else(|| "?".into());

            println!("  label={label:?}  id={id}  type={key_type}");
        }
    }
    Ok(())
}

fn key_type_name(kt: cryptoki::object::KeyType) -> String {
    use cryptoki::object::KeyType as KT;
    match kt {
        KT::RSA => "RSA".into(),
        KT::EC => "EC (ECDSA/ECDH)".into(),
        KT::EC_EDWARDS => "EC-Edwards (EdDSA)".into(),
        KT::EC_MONTGOMERY => "EC-Montgomery (X25519)".into(),
        KT::DSA => "DSA".into(),
        KT::DH => "DH".into(),
        KT::AES => "AES".into(),
        KT::DES3 => "DES3".into(),
        KT::GENERIC_SECRET => "Generic secret".into(),
        _ => format!("unknown ({kt:?})"),
    }
}

fn get_str_attr(
    session: &cryptoki::session::Session,
    handle: cryptoki::object::ObjectHandle,
    attr_type: cryptoki::object::AttributeType,
) -> Option<String> {
    use cryptoki::object::Attribute;
    session
        .get_attributes(handle, &[attr_type])
        .ok()?
        .into_iter()
        .find_map(|a| match a {
            // CKA_LABEL is a raw byte array; nShield always writes UTF-8 labels.
            Attribute::Label(bytes) => String::from_utf8(bytes).ok(),
            _ => None,
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A public key with the given MPIs, for the algorithm-policy tests.
    /// Only the material matters here; the creation time never participates
    /// in an algorithm check.
    fn public_key_with(
        algo: sequoia_openpgp::types::PublicKeyAlgorithm,
        mpis: sequoia_openpgp::crypto::mpi::PublicKey,
    ) -> sequoia_openpgp::packet::Key<
        sequoia_openpgp::packet::key::PublicParts,
        sequoia_openpgp::packet::key::UnspecifiedRole,
    > {
        sequoia_openpgp::packet::Key::V4(
            sequoia_openpgp::packet::key::Key4::<
                sequoia_openpgp::packet::key::PublicParts,
                sequoia_openpgp::packet::key::PrimaryRole,
            >::new(std::time::SystemTime::UNIX_EPOCH, algo, mpis)
            .unwrap()
            .role_into_unspecified(),
        )
    }

    fn rsa_key(
        bits: usize,
    ) -> sequoia_openpgp::packet::Key<
        sequoia_openpgp::packet::key::PublicParts,
        sequoia_openpgp::packet::key::UnspecifiedRole,
    > {
        use sequoia_openpgp::crypto::mpi;
        // A modulus of exactly `bits` bits: leading byte 0x80 sets the top
        // bit, which is what makes MPI::bits() report the nominal size.
        let mut n = vec![0xffu8; bits / 8];
        n[0] = 0x80;
        public_key_with(
            sequoia_openpgp::types::PublicKeyAlgorithm::RSAEncryptSign,
            mpi::PublicKey::RSA {
                e: mpi::MPI::new(&[0x01, 0x00, 0x01]),
                n: mpi::MPI::new(&n),
            },
        )
    }

    fn ecdsa_key(
        curve: sequoia_openpgp::types::Curve,
    ) -> sequoia_openpgp::packet::Key<
        sequoia_openpgp::packet::key::PublicParts,
        sequoia_openpgp::packet::key::UnspecifiedRole,
    > {
        use sequoia_openpgp::crypto::mpi;
        let len = curve.field_size().unwrap();
        let mut point = vec![0x04u8];
        point.extend(std::iter::repeat_n(0x01u8, len * 2));
        public_key_with(
            sequoia_openpgp::types::PublicKeyAlgorithm::ECDSA,
            mpi::PublicKey::ECDSA {
                curve,
                q: mpi::MPI::new(&point),
            },
        )
    }

    #[test]
    fn require_key_algo_matches_the_exact_size() {
        assert!(key_matches_algo(&rsa_key(4096), RequiredKeyAlgo::Rsa4096));
        assert!(key_matches_algo(&rsa_key(3072), RequiredKeyAlgo::Rsa3072));
        assert!(key_matches_algo(&rsa_key(2048), RequiredKeyAlgo::Rsa2048));
    }

    #[test]
    fn require_key_algo_is_exact_not_a_minimum() {
        // A stronger key is still the wrong key: the flag states which key is
        // in use, not a floor.  RSA-8192 must not satisfy an rsa4096 policy.
        assert!(!key_matches_algo(&rsa_key(8192), RequiredKeyAlgo::Rsa4096));
        assert!(!key_matches_algo(&rsa_key(3072), RequiredKeyAlgo::Rsa4096));
    }

    #[test]
    fn require_key_algo_does_not_confuse_rsa_with_ecdsa() {
        use sequoia_openpgp::types::Curve;
        // The EL9 case that motivates the flag: ECDSA where RSA was required
        // must be refused, because rpm 4.16 cannot verify it at all.
        assert!(!key_matches_algo(
            &ecdsa_key(Curve::NistP384),
            RequiredKeyAlgo::Rsa4096
        ));
        assert!(!key_matches_algo(&rsa_key(4096), RequiredKeyAlgo::P384));
    }

    #[test]
    fn require_key_algo_distinguishes_curves() {
        use sequoia_openpgp::types::Curve;
        assert!(key_matches_algo(
            &ecdsa_key(Curve::NistP256),
            RequiredKeyAlgo::P256
        ));
        assert!(key_matches_algo(
            &ecdsa_key(Curve::NistP384),
            RequiredKeyAlgo::P384
        ));
        assert!(!key_matches_algo(
            &ecdsa_key(Curve::NistP256),
            RequiredKeyAlgo::P384
        ));
    }

    #[test]
    fn describe_key_algo_reports_what_the_policy_names() {
        use sequoia_openpgp::types::Curve;
        // The diagnostic and the policy value share one vocabulary, so the
        // error message names something the operator can pass back verbatim.
        assert_eq!(describe_key_algo(&rsa_key(4096)), "RSA-4096");
        assert_eq!(
            describe_key_algo(&ecdsa_key(Curve::NistP384)),
            "ECDSA P-384"
        );
        assert_eq!(
            describe_key_algo(&rsa_key(4096)),
            RequiredKeyAlgo::Rsa4096.as_str()
        );
        assert_eq!(
            describe_key_algo(&ecdsa_key(Curve::NistP384)),
            RequiredKeyAlgo::P384.as_str()
        );
    }

    #[test]
    fn creation_time_omitted_is_an_error_not_epoch() {
        // Regression guard for the silent Unix-epoch default: a forgotten
        // --creation-time produced perfectly valid signatures carrying an
        // issuer fingerprint that resolved to no published key.
        let err = require_creation_time(None, "--creation-time", None)
            .expect_err("an omitted creation time must be rejected")
            .to_string();
        assert!(
            err.contains("--creation-time is required"),
            "error must name the missing flag, got: {err}"
        );
        assert!(
            err.contains("gentime"),
            "error must say where the value comes from, got: {err}"
        );
        assert!(
            err.contains("1970-01-01T00:00:00Z"),
            "error must spell out the explicit opt-in for the old behaviour, got: {err}"
        );
    }

    #[test]
    fn missing_creation_time_names_the_flag_it_was_asked_about() {
        // cert-export has two independent creation times; each must report
        // itself, not a generic message.
        let err = require_creation_time(None, "--subkey-creation-time", None)
            .unwrap_err()
            .to_string();
        assert!(
            err.starts_with("--subkey-creation-time is required"),
            "{err}"
        );
        assert!(
            err.contains("`--subkey-creation-time 1970-01-01T00:00:00Z`"),
            "the opt-in example must use the same flag, got: {err}"
        );
    }

    #[test]
    fn missing_creation_time_includes_the_per_command_hint() {
        let err = require_creation_time(None, "--creation-time", Some("HINT-MARKER"))
            .unwrap_err()
            .to_string();
        assert!(err.contains("HINT-MARKER"), "{err}");
    }

    #[test]
    fn creation_time_rfc3339_round_trip() {
        let t =
            require_creation_time(Some("2026-04-30T16:29:30Z"), "--creation-time", None).unwrap();
        let expected = humantime::parse_rfc3339("2026-04-30T16:29:30Z").unwrap();
        assert_eq!(t, expected);
    }

    #[test]
    fn creation_time_epoch_is_still_accepted_when_explicit() {
        // The escape hatch for a cert that really was published with the old
        // default: spell the epoch out.
        let t =
            require_creation_time(Some("1970-01-01T00:00:00Z"), "--creation-time", None).unwrap();
        assert_eq!(t, std::time::SystemTime::UNIX_EPOCH);
    }

    #[test]
    fn creation_time_garbage_rejected() {
        assert!(parse_rfc3339_time("--creation-time", "not a date").is_err());
        assert!(parse_rfc3339_time("--creation-time", "").is_err());
    }

    #[test]
    fn timestamp_error_names_the_flag_that_was_malformed() {
        // A bad --revocation-time used to report itself as a bad
        // --creation-time, sending the operator to the wrong flag.
        let err = parse_rfc3339_time("--revocation-time", "not a date")
            .unwrap_err()
            .to_string();
        assert!(err.contains("--revocation-time"), "{err}");
    }

    #[test]
    fn creation_time_requires_timezone() {
        // RFC 3339 requires an explicit timezone.  A bare datetime without 'Z'
        // or an offset is ambiguous and must be rejected so users don't
        // accidentally embed a localtime-interpreted timestamp in a published
        // certificate.
        assert!(parse_rfc3339_time("--creation-time", "2026-04-30T16:29:30").is_err());
    }

    #[test]
    fn validity_years_lands_on_calendar_anniversary() {
        // 5y from 2026-05-10T19:53:26Z must land at 2031-05-10T19:53:26Z
        // exactly — no 6h drift from the old Julian-year approximation.
        let creation = humantime::parse_rfc3339("2026-05-10T19:53:26Z").unwrap();
        let d = parse_validity("5y", creation).unwrap();
        let expiration = creation + d;
        let expected = humantime::parse_rfc3339("2031-05-10T19:53:26Z").unwrap();
        assert_eq!(expiration, expected);
    }

    #[test]
    fn validity_years_leap_count_changes_with_creation_date() {
        // 1y starting *before* Feb 29 of a leap year spans 366 days;
        // 1y starting *after* it spans 365.  The calendar form reflects
        // this asymmetry; the old fixed-365.25-day form did not.
        let before = humantime::parse_rfc3339("2024-02-15T12:00:00Z").unwrap();
        let after = humantime::parse_rfc3339("2024-03-01T12:00:00Z").unwrap();
        assert_eq!(
            parse_validity("1y", before).unwrap().as_secs(),
            366 * 86_400
        );
        assert_eq!(parse_validity("1y", after).unwrap().as_secs(), 365 * 86_400);
    }

    #[test]
    fn validity_years_feb29_falls_back_to_feb28() {
        // Creation on Feb 29 of a leap year + 1y lands on Feb 28 of the
        // following (non-leap) year.
        let creation = humantime::parse_rfc3339("2024-02-29T12:00:00Z").unwrap();
        let d = parse_validity("1y", creation).unwrap();
        let expiration = creation + d;
        let expected = humantime::parse_rfc3339("2025-02-28T12:00:00Z").unwrap();
        assert_eq!(expiration, expected);
    }

    #[test]
    fn validity_humantime_units() {
        // Days, weeks, hours go through humantime — not creation-dependent.
        let c = std::time::SystemTime::UNIX_EPOCH;
        assert_eq!(parse_validity("30d", c).unwrap().as_secs(), 30 * 86_400);
        assert_eq!(parse_validity("1w", c).unwrap().as_secs(), 7 * 86_400);
        assert_eq!(parse_validity("48h", c).unwrap().as_secs(), 48 * 3_600);
    }

    #[test]
    fn validity_default_is_5_years() {
        // The clap default value "5y" must parse cleanly.
        let c = humantime::parse_rfc3339("2026-05-10T19:53:26Z").unwrap();
        assert!(parse_validity("5y", c).is_ok());
    }

    #[test]
    fn validity_rejects_garbage() {
        let c = std::time::SystemTime::UNIX_EPOCH;
        assert!(parse_validity("forever", c).is_err());
        assert!(parse_validity("", c).is_err());
        assert!(parse_validity("xy", c).is_err());
        // Fractional years are no longer accepted — calendar arithmetic
        // is defined on whole years only.
        assert!(parse_validity("1.5y", c).is_err());
    }

    #[test]
    fn validity_rejects_negative() {
        let c = std::time::SystemTime::UNIX_EPOCH;
        assert!(parse_validity("-3y", c).is_err());
    }

    #[test]
    fn validity_rejects_zero() {
        // Zero validity = "expired immediately".  An easy fat-finger;
        // refuse rather than silently produce a dead-on-arrival cert.
        let c = std::time::SystemTime::UNIX_EPOCH;
        for s in ["0y", "0d", "0h", "0w", "0s", "0 days"] {
            let err = parse_validity(s, c).unwrap_err().to_string();
            assert!(
                err.contains("zero") && err.contains("--no-expiration"),
                "expected zero-validity rejection mentioning --no-expiration for {s:?}, got: {err}"
            );
        }
    }
}
